/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 chapel.glb 
*/

import React, { useRef } from "react";
import {
  useGLTF,
  MeshTransmissionMaterial,
  useTexture,
  useVideoTexture,
} from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  const { nodes, materials } = useGLTF("/glb/chapel.glb");
  const stainedGlassTexture = useTexture("/textures/stainedglass_swirl.jpg");
  // const purpleOceanTexture = useTexture('/textures/purple_oceans.jpg')
  const purpleOceanTexture = useVideoTexture("/videos/purple_oceans.mp4");

  const nPurpleOceanTexture = useTexture("/textures/n_purple_oceans.jpg");

  const groupRef = useRef();
  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 1;
    }
  });
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.candle.geometry} material={materials["default"]} />
      <mesh
        geometry={nodes.woman.geometry}
        material={materials["default.001"]}
      />
      <mesh
        geometry={nodes.table.geometry}
        material={materials["/mat/defaultMat"]}
      />
      <mesh
        geometry={nodes.candle002.geometry}
        material={materials["default"]}
      />
      <mesh
        geometry={nodes.Object_461.geometry}
        material={materials.FrontCol}
      />
      <mesh
        geometry={nodes.Object_462.geometry}
        material={materials.Roofin02}
      />
      <mesh
        geometry={nodes.Object_464.geometry}
        material={materials.Wood_Ven}
      />
      <mesh geometry={nodes.roof.geometry} material={materials.roof} />
      <mesh
        geometry={nodes.lowerroof.geometry}
        material={materials.lowerroof}
      />
      <mesh
        geometry={nodes.altar.geometry}
        material={materials.altar}
        position={[0.076, 2.692, -8.917]}
        scale={0.951}
      />
      <mesh
        geometry={nodes.innerwalls.geometry}
        material={materials.innerwalls}
      />
      <mesh
        geometry={nodes.Object_454.geometry}
        material={materials.innerwalls}
      />
      <mesh
        geometry={nodes.Object_456.geometry}
        material={materials.Transluc}
      />
      <mesh
        geometry={nodes.Object_457.geometry}
        material={materials.Roofin02}
      />
      <mesh
        geometry={nodes.Object_458.geometry}
        material={materials.Wood_Boa}
      />
      <mesh
        geometry={nodes.Object_459.geometry}
        material={materials.Wood_Boa}
      />
      <mesh
        geometry={nodes.Object_460.geometry}
        material={materials.Wood_Boa}
      />
      <mesh
        geometry={nodes.Object_476.geometry}
        material={materials.Wood_Ven}
      />
      <mesh
        geometry={nodes.Object_478.geometry}
        material={materials.Wood_F01}
      />
      <mesh
        geometry={nodes.Object_479.geometry}
        material={materials.Wood_Lum}
      />
      <mesh
        geometry={nodes.Object_467.geometry}
        material={materials.Foregrou}
      />
      <mesh
        geometry={nodes.Object_468.geometry}
        material={materials.Wood_Lum}
      />
      <mesh
        geometry={nodes.Object_469.geometry}
        material={materials.Wood_Ven}
      />
      <mesh
        geometry={nodes.Object_473.geometry}
        material={materials.Wood_F02}
      />
      <mesh
        geometry={nodes.Object_474.geometry}
        material={materials.Wood_F02}
      />
      <mesh
        geometry={nodes.Object_482.geometry}
        material={materials.Foregrou}
      />
      <mesh geometry={nodes.Object_484.geometry} material={materials.Roofing} />
      <mesh geometry={nodes.MainWindow.geometry}>
        <MeshTransmissionMaterial
          transmission={1}
          map={purpleOceanTexture}
          side={2}
          roughness={0.35}
          normalMap={nPurpleOceanTexture}
          thickness={0.5}
          transmission={0.9}
          ior={1.3}
          distortion={2}
          distortionScale={1}
        />
      </mesh>
      <mesh geometry={nodes.Windows.geometry}>
        <MeshTransmissionMaterial
          transmission={1}
          map={stainedGlassTexture}
          side={2}
          roughness={0.35}
          thickness={0.3}
          ior={1.3}
          distortion={1.5}
          distortionScale={0.9}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/chapel.glb");
